### ISSUE TITLE
mp_forms 5.0

### ISSUE THREAD

**Issue by Toflar** [markocupic/sac-event-feedback#1]
Hey, I don't know why exactly you required `terminal42/contao-mp_forms` in your `composer.json` but apparently you're somewhat using it for your bundle. In case you're integrating with some code, version 5 is around the corner: https://github.com/terminal42/contao-mp_forms/pull/66

This is just an info - feel free to close the issue if it has no relevance :-)

**Comment by Toflar** [comment]
I found your project because of https://packagist.org/packages/terminal42/contao-mp_forms/dependents?order_by=downloads

**Comment by markocupic** [comment]
@Toflar thank you!
